### ISSUE TITLE
TODO/Img Link

### ISSUE THREAD

**Issue by Turtle-Hwan** [LightlessStar/DVM#1]
- [x] 따로 서버(클라우드 or 라즈베리) 파서 서버 상에서 Jenkins(CI) / Test 환경 구축

# <과제> 만들어야 할 것 : Unit Test, CI 환경 자동화 (Jenkins)
- CI 환경 구축 툴 활용 -> Code version control + JUnit
- JUnit이 private workflow 내에서도 되어야 하고, Jenkins에 올려서도 되어야 한다.
- 개발 진행 시 CI까지 같이 진행한다.

- Build 도구는 Maven or Gradle

**Comment by Turtle-Hwan** [comment]
![image](https://github.com/LightlessStar/DVM/assets/67897841/b7ec87a3-1683-43fc-92fa-a8eb13e6c74b)

**Comment by swkim12345** [comment]
<svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32" data-view-component="true" class="octicon octicon-mark-github v-align-middle color-fg-default">
    <path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path>
</svg>

**Comment by swkim12345** [comment]
<svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32" data-view-component="true" class="octicon octicon-mark-github v-align-middle color-fg-default">
    <path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path>
</svg>

**Comment by Turtle-Hwan** [comment]
`<svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32" data-view-component="true" class="octicon octicon-mark-github v-align-middle color-fg-default">
    <path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path>
</svg>`

**Comment by Turtle-Hwan** [comment]
![image](https://github.com/LightlessStar/DVM/assets/67897841/50c919d4-b36e-454d-8efd-8b524e7860f4)

**Comment by Turtle-Hwan** [comment]
![image](https://github.com/LightlessStar/DVM/assets/67897841/dcbc2d08-a68c-41b1-8fda-eae7f6fb61f4)

![image](https://github.com/LightlessStar/DVM/assets/67897841/86481762-077a-4105-8412-d942eacff145)
![image](https://github.com/LightlessStar/DVM/assets/67897841/049e576b-6a3c-44ab-92b5-288ebd078e2e)

**Comment by Turtle-Hwan** [comment]
![image](https://github.com/LightlessStar/DVM/assets/67897841/29608041-3e5c-4ef1-8850-b884b1f36b51)
![image](https://github.com/LightlessStar/DVM/assets/67897841/d94d5035-d242-4bab-8533-04abc2a599f8)

**Comment by Turtle-Hwan** [comment]
proxmox가상머신

**Comment by Turtle-Hwan** [comment]
![image](https://github.com/LightlessStar/DVM/assets/67897841/7ace015f-4faf-4dbb-8920-06ef9f1bed00)

**Comment by Turtle-Hwan** [comment]
# Use Cases
#### 1-a, b, c, d, e
![image](https://github.com/LightlessStar/DVM/assets/67897841/e7386ddf-3535-40d5-8758-fd107ce477b5)
![image](https://github.com/LightlessStar/DVM/assets/67897841/6898c15f-105b-452b-a5c4-8c6c431b4329)
![image](https://github.com/LightlessStar/DVM/assets/67897841/2d248bc4-3b0a-45e8-8f72-75ed698d75a5)
![image](https://github.com/LightlessStar/DVM/assets/67897841/15f78fa3-12b4-415b-81a1-af57adcb1014)
![image](https://github.com/LightlessStar/DVM/assets/67897841/d3d1388c-a736-4e7a-803a-6d11aa4a5732)
#### 2-a, b, c, d
![image](https://github.com/LightlessStar/DVM/assets/67897841/6f390b27-8ecd-4bc8-a32d-13fda2a4872d)
![image](https://github.com/LightlessStar/DVM/assets/67897841/2aaa85f6-fa2f-46d9-82d1-a98341525386)
![image](https://github.com/LightlessStar/DVM/assets/67897841/c1840830-c138-4f71-a8b2-4e17936aff0f)
![image](https://github.com/LightlessStar/DVM/assets/67897841/e686f886-fed4-422c-9f1e-03cead05abc9)
#### 3-a, b
![image](https://github.com/LightlessStar/DVM/assets/67897841/65c1c6ca-14f8-4f43-bb82-75a2346a98d5)
![image](https://github.com/LightlessStar/DVM/assets/67897841/dc10abb5-20c7-41a3-81d4-58dff08169a0)
#### 4-a, b
![image](https://github.com/LightlessStar/DVM/assets/67897841/8b995d96-ac1a-4aa9-9565-8ff21b454ee5)
![image](https://github.com/LightlessStar/DVM/assets/67897841/9f1fc35a-0a65-4df1-b778-5cc302534c8f)

**Comment by Turtle-Hwan** [comment]
### Sequence Diagrams
#### 1
![image](https://github.com/LightlessStar/DVM/assets/67897841/b9e06d7b-c472-463b-a5b8-88a39fda5ccd)
![image](https://github.com/LightlessStar/DVM/assets/67897841/1ad6fc07-cfdb-4753-9fd3-a052fffd9121)
![image](https://github.com/LightlessStar/DVM/assets/67897841/a726c0ba-0912-4529-a868-d1fbc930ddd0)
![image](https://github.com/LightlessStar/DVM/assets/67897841/f99072be-9b39-4bd9-a726-27e947e09958)
![image](https://github.com/LightlessStar/DVM/assets/67897841/9c1c5ff2-4f2f-4f5a-b0f7-36a47bd4f7ba)
#### 2
![image](https://github.com/LightlessStar/DVM/assets/67897841/43c32a05-1ed9-4728-b65c-c618f72da2ce)
![image](https://github.com/LightlessStar/DVM/assets/67897841/59a74596-d474-4a1b-b216-59362baf3a89)
![image](https://github.com/LightlessStar/DVM/assets/67897841/ac9d8bb8-60b1-4c03-a2ea-782c07e19add)
![image](https://github.com/LightlessStar/DVM/assets/67897841/0c5af8ed-b8ea-490c-ba2b-6110818ad4df)
#### 3
![image](https://github.com/LightlessStar/DVM/assets/67897841/822f6e0e-c8fd-403e-a49b-0a0d97fe7559)
![image](https://github.com/LightlessStar/DVM/assets/67897841/28df8e73-d8da-4638-aa98-fc5eb8b336a9)
#### 4
![image](https://github.com/LightlessStar/DVM/assets/67897841/5f0a33ad-703b-4e34-ad76-1265331f5e4d)
![image](https://github.com/LightlessStar/DVM/assets/67897841/14311496-f8e3-4039-a039-6740042163a8)
